// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MySqlEfCoreConsole;
using System;

namespace MySqlEfCoreConsole.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20180404125803_AddedMetadataTable")]
    partial class AddedMetadataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("MySqlEfCoreConsole.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Language");

                    b.Property<int>("Pages");

                    b.Property<int?>("PublisherID");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ISBN");

                    b.HasIndex("PublisherID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("MySqlEfCoreConsole.MetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DataSeeded");

                    b.Property<DateTime?>("StatusAt")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MetaData");
                });

            modelBuilder.Entity("MySqlEfCoreConsole.Publisher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("MySqlEfCoreConsole.Book", b =>
                {
                    b.HasOne("MySqlEfCoreConsole.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherID");
                });
#pragma warning restore 612, 618
        }
    }
}
